=== api-evangelist/twitter/json-schema/x-api-\1ctivity-\1ubscription-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/twitter/refs/heads/main/json-schema/x-api-\\1ctivity-\\1ubscription-schema.json",
  "title": "ActivitySubscription",
  "description": "An XActivity subscription.",
  "type": "object",
  "properties": {
    "created_at": {
      "type": "string",
      "format": "date-time",
      "example": "2026-04-17T12:00:00Z"
    },
    "event_type": {
      "type": "string",
      "example": "standard"
    },
    "filter": {
      "type": "object",
      "description": "An XAA subscription filter.",
      "properties": {
        "direction": {
          "type": "string",
          "description": "Optional direction filter for directional events.",
          "enum": [
            "inbound",
            "outbound"
          ],
          "example": "inbound"
        },
        "keyword": {
          "$ref": "#/components/schemas/Keyword"
        },
        "user_id": {
          "$ref": "#/components/schemas/UserId"
        }
      },
      "additionalProperties": false
    },
    "subscription_id": {
      "type": "string",
      "description": "The unique identifier of this subscription.",
      "pattern": "^[0-9]{1,19}$",
      "example": "1146654567674912769"
    },
    "tag": {
      "type": "string",
      "example": "example_tag"
    },
    "updated_at": {
      "type": "string",
      "format": "date-time",
      "example": "2026-04-17T12:00:00Z"
    },
    "webhook_id": {
      "type": "string",
      "description": "The unique identifier of this webhook config.",
      "pattern": "^[0-9]{1,19}$",
      "example": "1146654567674912769"
    }
  },
  "required": [
    "subscription_id",
    "event_type",
    "filter",
    "created_at",
    "updated_at"
  ]
}

=== api-evangelist/twitter/examples/x-api-\1ctivity-\1ubscription-example.json
{
  "created_at": "2026-04-17T12:00:00Z",
  "event_type": "standard",
  "filter": {
    "direction": "inbound",
    "keyword": "example_value",
    "user_id": "1234567890123456789"
  },
  "subscription_id": "1146654567674912769",
  "tag": "example_tag",
  "updated_at": "2026-04-17T12:00:00Z",
  "webhook_id": "1146654567674912769"
}
